### PR TITLE
Added SSH keys support

### PR DESCRIPTION
**Pull request by aajdinov**
Added POCO classes, client endpoint, and unit tests.

### CODE REVIEW

**Comment by aajdinov** [comment]
@edevenport - I was't able to assign a reviewer on this PR.
@alibazlamit - Ali, would you please review the PR? Thank you.

**Comment by jasmingacic** [comment]
Readme needs to be updated

**Comment by jasmingacic** [comment]
@aajdinov the PR should go first to StackPointCloud repository and then to 1and1. Can you fix this.

**Comment by aajdinov** [comment]
@jasmingacic I've updated the readme and opened a PR on StackPointCloud repository (closing this PR).
Thanks

**Pull request closed without merging**
