### PR TITLE
Added block storages support

### PR DESCRIPTION
**Pull request by aajdinov**
Added POCO classes, client endpoint, and unit tests.

### CODE REVIEW

**Comment by aajdinov** [comment]
@edevenport - I was not able to assign a reviewer on this PR.
@alibazlamit - Would you please review this PR? Thank you.

**Comment by jasmingacic** [comment]
@aajdinov The PR should go first to StackPointCloud repository. Can you have it switched? 
Thanks

**Comment by jasmingacic** [comment]
Readme needs to be updated

**Comment by aajdinov** [comment]
@jasmingacic I've opened a PR on StackPointCloud repository (closing this PR).
Thanks

**Pull request closed without merging**
